MESSAGES = {
    'uz': {
        'welcome': "👋 <b>Assalomu alaykum! Mine Botga xush kelibsiz!</b>\n\nMen Minecraft kanalingiz uchun postlar tayyorlashda yordam beraman.\n\n<b>Nima qila olaman?</b>\n1. Mod/Karta havolasidan chiroyli post yaratish.\n2. Rasmlarga avtomatik logo qo'yish.\n3. Postlarni navbatga qo'yish va rejalashtirish.\n\nBoshlash uchun mod havolasini yuboring yoki rasm yuklang!",
        'generation_start': "⏳ <b>Post tayyorlanmoqda...</b>",
        'processing_photo': "🎨 <b>Rasm qayta ishlanmoqda...</b>",
        'file_attached': "✅ Fayl biriktirildi! (Jami: <b>{count}</b>)",
        'no_draft': "❌ Faol qoralama topilmadi.",
        'cancel_msg': "❌ Amaliyot bekor qilindi.",
        'text_updated': "✅ Matn yangilandi!",
        'scheduled': "📅 {time} ga rejalashtirildi!",
        'published': "🚀 Kanalga muvaffaqiyatli chop etildi!",
        'err_draft': "⚠️ Qoralama eskirgan yoki topilmadi.",
        'err_publish': "❌ Chop etishda xatolik yuz berdi!",
        'enter_text': "✍️ Post uchun yangi matnni yuboring:",
        'enter_time': "📅 Sana va vaqtni kiriting (KK.OO SS:DD)\nMasalan: <code>25.04 15:30</code>",
        'invalid_date': "❌ Sana formati noto'g'ri. Qaytadan urinib ko'ring:",
        'rewriting': "⏳ Matn qayta yozilmoqda...",
        'smart_queue_added': "🧠 Post aqlli navbatga qo'shildi!",
        'choose_action': "Tanlang:",
        'album_loading': "📸 Albom yuklanmoqda...",
        'album_processing': "🎨 Albom rasmlari qayta ishlanmoqda {i}/{total}...",
    },
    'ru': {
        'welcome': "👋 <b>Добро пожаловать в Mine Bot!</b>\n\nЯ помогу тебе создавать посты для твоего Minecraft-канала.\n\n<b>Что я умею?</b>\n1. Создавать красивые посты по ссылке на мод.\n2. Автоматически накладывать логотип на фото.\n3. Планировать посты в очередь.\n\nДля начала отправь ссылку на мод или фото!",
        'generation_start': "⏳ <b>Генерирую пост...</b>",
        'processing_photo': "🎨 <b>Обрабатываю фото...</b>",
        'file_attached': "✅ Файл прикреплен! (Всего: <b>{count}</b>)",
        'no_draft': "❌ Активный черновик не найден.",
        'cancel_msg': "❌ Действие отменено.",
        'text_updated': "✅ Текст обновлен!",
        'scheduled': "📅 Запланировано на {time}!",
        'published': "🚀 Успешно опубликовано!",
        'err_draft': "⚠️ Черновик устарел или не найден.",
        'err_publish': "❌ Ошибка при публикации!",
        'enter_text': "✍️ Отправь новый текст для поста:",
        'enter_time': "📅 Введи дату и время (ДД.ММ ЧЧ:ММ)\nПример: <code>25.04 15:30</code>",
        'invalid_date': "❌ Неверный формат даты. Попробуй еще раз:",
        'rewriting': "⏳ Переписываю текст...",
        'smart_queue_added': "🧠 Пост добавлен в умную очередь!",
        'choose_action': "Выберите действие:",
        'album_loading': "📸 Загружаю альбом...",
        'album_processing': "🎨 Обработка фото в альбоме {i}/{total}...",
    },
    'en': {
        'welcome': "👋 <b>Welcome to Mine Bot!</b>\n\nI'll help you create posts for your Minecraft channel.\n\n<b>What can I do?</b>\n1. Create beautiful posts from a mod link.\n2. Automatically add logos to photos.\n3. Schedule posts in a queue.\n\nTo start, send a mod link or a photo!",
        'generation_start': "⏳ <b>Generating post...</b>",
        'processing_photo': "🎨 <b>Processing photo...</b>",
        'file_attached': "✅ File attached! (Total: <b>{count}</b>)",
        'no_draft': "❌ No active draft found.",
        'cancel_msg': "❌ Action cancelled.",
        'text_updated': "✅ Text updated!",
        'scheduled': "📅 Scheduled for {time}!",
        'published': "🚀 Successfully published!",
        'err_draft': "⚠️ Draft expired or not found.",
        'err_publish': "❌ Error during publishing!",
        'enter_text': "✍️ Send new text for the post:",
        'enter_time': "📅 Enter date and time (DD.MM HH:MM)\nExample: <code>25.04 15:30</code>",
        'invalid_date': "❌ Invalid date format. Please try again:",
        'rewriting': "⏳ Rewriting text...",
        'smart_queue_added': "🧠 Post added to smart queue!",
        'choose_action': "Choose action:",
        'album_loading': "📸 Loading album...",
        'album_processing': "🎨 Processing album photo {i}/{total}...",
    }
}

BUTTONS = {
    'uz': {
        'create': "📝 Post yaratish",
        'open_panel': "🌐 Panelni ochish",
        'cancel': "❌ Bekor qilish",
        'back': "⬅️ Orqaga",
        'smart_queue': "🧠 Aqlli navbat",
        'now': "🚀 Hozir",
        'later': "📅 Keyinroq",
        'edit': "✏️ Tahrirlash",
        'rewrite': "✨ Qayta yozish",
        'delete': "❌ O'chirish",
        'short': "Коротко", # Groq logic uses these
        'long': "Подробно",
        'exact': "📅 Aniq vaqt"
    },
    'ru': {
        'create': "📝 Создать пост",
        'open_panel': "🌐 Открыть панель",
        'cancel': "❌ Отмена",
        'back': "⬅️ Назад",
        'smart_queue': "🧠 Умная очередь",
        'now': "🚀 Сейчас",
        'later': "📅 Позже",
        'edit': "✏️ Правка",
        'rewrite': "✨ Переписать",
        'delete': "❌ Удалить",
        'short': "Коротко",
        'long': "Подробно",
        'exact': "📅 Точная дата"
    },
    'en': {
        'create': "📝 Create Post",
        'open_panel': "🌐 Open Panel",
        'cancel': "❌ Cancel",
        'back': "⬅️ Back",
        'smart_queue': "🧠 Smart Queue",
        'now': "🚀 Now",
        'later': "📅 Later",
        'edit': "✏️ Edit",
        'rewrite': "✨ Rewrite",
        'delete': "❌ Delete",
        'short': "Short",
        'long': "Long",
        'exact': "📅 Exact Time"
    }
}
